/** Declaration file generated by dts-gen */

declare module "onvif" {
  export class Cam {
    constructor(
      options: {
        hostname: string;
        username?: string;
        password?: string;
        port?: number;
      },
      callback?: (this: Cam, err: Error) => void
    );

    absoluteMove(
      options: {
        profileToken?: string;
        x?: number;
        y?: number;
        zoom?: number;
        speed?: number;
      },
      callback?: (this: Cam, err: Error) => void
    ): void;

    getStreamUri(
      options: {
        profileToken?: string;
        stream?: string;
        protocol?: string;
      },
      callback?: (this: Cam, err: Error, streamInfo: {
        invalidAfterConnect: boolean;
        invalidAfterReboot: boolean;
        timeout: string;
        uri: string;
        invalidAfterConnect: boolean;
      }) => void
    ): void;

    connect(callback: (this: Cam, err: Error) => void): void;

  }
}
